<?

$path = 'PHPMailer';
set_include_path(get_include_path() . PATH_SEPARATOR . $path);



use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require $path.'/src/Exception.php';
require $path.'/src/PHPMailer.php';
require $path.'/src/SMTP.php';

function sendMail($sender='test_sender', $recipient='test', $body='test body'){

	$mail = new PHPMailer();
	$mail->isSMTP();
	$mail->SMTPAuth = true;

	$mail->SMTPSecure = 'tls';
	$mail->Host = 'smtp.gmail.com';
	$mail->Port = 587;
	$mail->Username = "michael@abehave.com";
	$mail->Password = "annakai3";
	$mail->setFrom('michael@abehave.com', 'ABAIT');

	//indp-abait@my-project-288320.iam.gserviceaccount.com

	// for testing

	// $mail->Host = 'smtp.mailtrap.io';
	// $mail->Username = '29b5f846f8c831'; //paste one generated by Mailtrap
	// $mail->Password = '3c8564078f7257'; //paste one generated by Mailtrap
	// $mail->SMTPSecure = 'tls';
	// $mail->Port = 2525;

	// $mail->setFrom('info@mailtrap.io', 'Mailtrap');
	$mail->addReplyTo('michael@abehave.com', 'ABAIT');
	$mail->addAddress('michael@abehave.com', 'mike1'); 
	$mail->addCC('suzanne@abehave.com', 'Suzanne');
	// $mail->addBCC('bcc1@example.com', 'mike3');


	$mail->Subject = 'Emergency Intervention Required';

	$mail->isHTML(true);


	$mailContent = $body;
	$mail->Body = $mailContent;

	if($mail->send()){
	    echo '<p>Message has been sent</p>';
	}else{
	    echo 'Message could not be sent.';
	    echo 'Mailer Error: ' . $mail->ErrorInfo;
	}
}
?>