<?

$path = 'PHPMailer';
set_include_path(get_include_path() . PATH_SEPARATOR . $path);



use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require $path.'/src/Exception.php';
require $path.'/src/PHPMailer.php';
require $path.'/src/SMTP.php';

function sendMail($sender='test_sender', $recipient='test', $body='test body'){

	$mail = new PHPMailer();

	// $mail->SMTPSecure = 'tls';
	// $mail->Host = 'smtp.gmail.com';
	$mail->Port = 587;



	// for testing
	$mail->isSMTP();
	$mail->Host = 'smtp.mailtrap.io';
	$mail->SMTPAuth = true;
	$mail->Username = '29b5f846f8c831'; //paste one generated by Mailtrap
	$mail->Password = '3c8564078f7257'; //paste one generated by Mailtrap
	$mail->SMTPSecure = 'tls';
	$mail->Port = 2525;

	$mail->setFrom('info@mailtrap.io', 'Mailtrap');
	$mail->addReplyTo('info@mailtrap.io', 'Mailtrap');
	$mail->addAddress('recipient1@mailtrap.io', 'mike1'); 
	$mail->addCC('cc1@example.com', 'mike2');
	$mail->addBCC('bcc1@example.com', 'mike3');


	$mail->Subject = 'Emergency Intervention Required';

	$mail->isHTML(true);


	$mailContent = $body;
	$mail->Body = $mailContent;

	if($mail->send()){
	    echo 'Message has been sent';
	}else{
	    echo 'Message could not be sent.';
	    echo 'Mailer Error: ' . $mail->ErrorInfo;
	}
}
?>